# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Grain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Grain
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'

  pod 'GoogleSignIn', '~> 6.2.4'
  pod 'GoogleSignInSwiftSupport'
  pod 'NMapsMap'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'Kingfisher'
end
